FROM emby/embyserver:4.7.13.0

RUN wget -O /system/Emby.Server.Implementations.dll https://github.com/kissyouhunter/Tools/raw/main/emby/4.7.13.0/Emby.Server.Implementations.dll \
    wget -O /system/Emby.Web.dll https://github.com/kissyouhunter/Tools/raw/main/emby/4.7.13.0/Emby.Web.dll \    
    wget -O /system/MediaBrowser.Model.dll https://github.com/kissyouhunter/Tools/raw/main/emby/4.7.13.0/MediaBrowser.Model.dll \
    wget -O /system/dashboard-ui/embypremiere/embypremiere.js https://github.com/kissyouhunter/Tools/raw/main/emby/4.7.13.0/dashboard-ui/embypremiere/embypremiere.js \
    wget -O /system/dashboard-ui/modules/emby-apiclient/connectionmanager.js https://github.com/kissyouhunter/Tools/raw/main/emby/4.7.13.0/dashboard-ui/modules/emby-apiclient/connectionmanager.js
